version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-nest-app
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-network

  redis:
    image: redis:7
    container_name: redis-nest-app
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge

volumes:
  pgdata:
